In [1]:
import numpy as np
import pandas as pd

CREATING DATAFRAMES

In [5]:
data = {
    'Name': ['John', 'Krish', 'harman', 'rai'],
    'Age': [21, 19, 21, 21],
    'City': ['basi', 'police line', 'bajwara', 'jct'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

     Name  Age         City  Salary
0    John   21         basi   65000
1   Krish   19  police line   70000
2  harman   21      bajwara   62000
3     rai   21          jct   85000

In [25]:
data_list = {
    'Name': ['John', 'Krish', 'harman', 'rai'],
    'Age': [21, 19, 21, 21],
    'City': ['basi', 'police line', 'bajwara', 'jct'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns)
df2

     Name  Age         City  Salary
0    John   21         basi   65000
1   Krish   19  police line   70000
2  harman   21      bajwara   62000
3     rai   21          jct   85000

SELECTING AND INDEXING

In [10]:
df

     Name  Age         City  Salary
0    John   21         basi   65000
1   Krish   19  police line   70000
2  harman   21      bajwara   62000
3     rai   21          jct   85000

In [14]:
df[["Name","Salary"]]

     Name  Salary
0    John   65000
1   Krish   70000
2  harman   62000
3     rai   85000

In [ ]:
#creating s new column

df["accupation"] = ["doctor","eng.","doctor","eng."]
df

     Name  Age         City  Salary accupation
0    John   21         basi   65000     doctor
1   Krish   19  police line   70000       eng.
2  harman   21      bajwara   62000     doctor
3     rai   21          jct   85000       eng.

In [18]:
#deleting the column
df.drop('accupation', axis= 1)

     Name  Age         City  Salary
0    John   21         basi   65000
1   Krish   19  police line   70000
2  harman   21      bajwara   62000
3     rai   21          jct   85000

In [21]:
#inplace is used to delete the data permanently
#selecting the rows
df
df.loc[[0,1]]

    Name  Age         City  Salary accupation
0   John   21         basi   65000     doctor
1  Krish   19  police line   70000       eng.

In [23]:
#selecting the subsets of rows and column
df.loc[[2,3]][["Age","Salary"]]

   Age  Salary
2   21   62000
3   21   85000

In [24]:
#conditional selection
df[df["Age"]>20]

     Name  Age     City  Salary accupation
0    John   21     basi   65000     doctor
2  harman   21  bajwara   62000     doctor
3     rai   21      jct   85000       eng.